#!/usr/bin/env bash
# Print deploy/backend.env from the GitHub environment secrets and variables
# the Deploy workflow exports. Values are single-quoted so Docker Compose takes
# them literally (no ${...} interpolation).
set -euo pipefail

missing=()
for name in APP_DOMAIN DATABASE_URL OUTBOX_ENCRYPTION_KEY EMAIL_FROM_ADDRESS; do
  [[ -n "${!name:-}" ]] || missing+=("$name")
done
if (( ${#missing[@]} )); then
  echo "::error::Missing required production settings: ${missing[*]}" >&2
  exit 1
fi
if [[ "${EMAIL_BACKEND:-console}" == smtp && -z "${SMTP_HOST:-}" ]]; then
  echo "::error::EMAIL_BACKEND is smtp but SMTP_HOST is empty" >&2
  exit 1
fi

emit() {
  local name="$1" value="$2"
  if [[ "$value" == *"'"* || "$value" == *$'\n'* ]]; then
    echo "::error::$name must not contain single quotes or line breaks" >&2
    exit 1
  fi
  printf "%s='%s'\n" "$name" "$value"
}

echo "# Generated by the Deploy workflow from the GitHub 'production' environment."
echo "# Do not edit on the server: it is overwritten on every deploy."

# Fixed for production; the backend refuses to start without these.
emit ENVIRONMENT production
emit DEBUG false
emit SESSION_COOKIE_SECURE true
# The frontend bundle reads the CSRF cookie by this name, so it is not configurable.
emit SESSION_COOKIE_NAME transpire_session
emit CSRF_COOKIE_NAME transpire_csrf
emit SSO_SELECTION_COOKIE_NAME transpire_sso_selection

emit DATABASE_URL "$DATABASE_URL"
emit OUTBOX_ENCRYPTION_KEY "$OUTBOX_ENCRYPTION_KEY"

# Derived from APP_DOMAIN unless explicitly overridden.
emit ALLOWED_HOSTS "${ALLOWED_HOSTS:-$APP_DOMAIN,localhost,127.0.0.1}"
emit CORS_ORIGINS "${CORS_ORIGINS:-https://$APP_DOMAIN}"
emit CORS_ORIGIN_REGEX "${CORS_ORIGIN_REGEX:-}"
emit PUBLIC_APP_URL "${PUBLIC_APP_URL:-https://$APP_DOMAIN}"
emit PUBLIC_API_URL "${PUBLIC_API_URL:-https://$APP_DOMAIN/api/v1}"

emit EMAIL_BACKEND "${EMAIL_BACKEND:-console}"
emit EMAIL_FROM_ADDRESS "$EMAIL_FROM_ADDRESS"
emit EMAIL_FROM_NAME "${EMAIL_FROM_NAME:-TRANSPIRE}"
emit SMTP_HOST "${SMTP_HOST:-}"
emit SMTP_PORT "${SMTP_PORT:-587}"
emit SMTP_USERNAME "${SMTP_USERNAME:-}"
emit SMTP_PASSWORD "${SMTP_PASSWORD:-}"
emit SMTP_START_TLS "${SMTP_START_TLS:-true}"
emit SMTP_USE_TLS "${SMTP_USE_TLS:-false}"
emit SMTP_TIMEOUT_SECONDS "${SMTP_TIMEOUT_SECONDS:-15}"

emit ENTRA_CLIENT_ID "${ENTRA_CLIENT_ID:-}"
emit ENTRA_CLIENT_SECRET "${ENTRA_CLIENT_SECRET:-}"
emit OIDC_STATE_MINUTES "${OIDC_STATE_MINUTES:-10}"
emit SSO_RECOVERY_MINUTES "${SSO_RECOVERY_MINUTES:-15}"

emit SESSION_HOURS "${SESSION_HOURS:-12}"
emit REMEMBERED_SESSION_DAYS "${REMEMBERED_SESSION_DAYS:-30}"
emit PASSWORD_RESET_MINUTES "${PASSWORD_RESET_MINUTES:-30}"
emit INVITATION_EXPIRY_HOURS "${INVITATION_EXPIRY_HOURS:-48}"
emit WORKSPACE_SELECTION_MINUTES "${WORKSPACE_SELECTION_MINUTES:-5}"

emit SIGN_IN_RATE_LIMIT "${SIGN_IN_RATE_LIMIT:-10}"
emit PASSWORD_RESET_RATE_LIMIT "${PASSWORD_RESET_RATE_LIMIT:-5}"
emit AUTH_RATE_WINDOW_SECONDS "${AUTH_RATE_WINDOW_SECONDS:-900}"
emit AUTH_RATE_BLOCK_SECONDS "${AUTH_RATE_BLOCK_SECONDS:-900}"
emit ACCOUNT_LOCKOUT_ATTEMPTS "${ACCOUNT_LOCKOUT_ATTEMPTS:-5}"
emit ACCOUNT_LOCKOUT_MINUTES "${ACCOUNT_LOCKOUT_MINUTES:-15}"

emit OUTBOX_MAX_ATTEMPTS "${OUTBOX_MAX_ATTEMPTS:-5}"
emit OUTBOX_RETRY_BASE_SECONDS "${OUTBOX_RETRY_BASE_SECONDS:-30}"
emit OUTBOX_LEASE_SECONDS "${OUTBOX_LEASE_SECONDS:-300}"

emit FX_API_BASE_URL "${FX_API_BASE_URL:-https://api.frankfurter.dev/v2}"
emit FX_CACHE_MINUTES "${FX_CACHE_MINUTES:-360}"
